### ISSUE TITLE
I Can't Create a New Folder in the MyThemes Directory

### ISSUE THREAD

**Issue by thecodeclimber** [knut-erik/gitpod-wp-mariadb#1]
I can't create a folder (or files) in the MyThemes directory.  When I try to create a new folder, I get the following message:

```
Error: EACCES: permission denied, mkdir '/workspace/gitpod-wp-mariadb/mythemes/newtheme''
```

If I try and create a new file, I get this message:

```
Unable to write file 'vscode-remote://knuterik-gitpodwpmariad-c4ja97i73k9.ws-us59.gitpod.io/workspace/gitpod-wp-mariadb/mythemes/newfile.php' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/workspace/gitpod-wp-mariadb/mythemes/newfile.php')
```

Any idea why I am getting these errors messages and what I can in order to create folders and files?  

Thanks.

**Comment by knu73r1k** [comment]
Thanks @thecodeclimber - I've fixed this now in the .gitpod.yml file, by changing the ownership back to the gitpod user. The wordpress container assign www-data group to own the directory, thus you were not able to create dirs. Closing issue.
